import numpy as np 
import matplotlib.pyplot as plt 

x_ref,rho_ref,u_ref,p_ref,alpha_1_ref = np.loadtxt('ref.csv',delimiter=',',unpack=True,skiprows=1)
x_tvd,rho_tvd,u_tvd,p_tvd,alpha_1_tvd = np.loadtxt('1p6.csv',delimiter=',',unpack=True,skiprows=1)
x_thinc,rho_thinc,u_thinc,p_thinc,alpha_1_thinc = np.loadtxt('thinc-nn.csv',delimiter=',',unpack=True,skiprows=1)

plt.figure(1)
plt.plot(x_ref,rho_ref,linewidth=1.5,color='black',label='Reference')
plt.plot(x_tvd,rho_tvd,linewidth=1.5,label='TVD (van-Leer)')
plt.plot(x_thinc,rho_thinc,linewidth=1.5,label='THINC')
plt.xlim(-5,5)
plt.xlabel(r'$x$')
plt.ylabel(r'$\rho$')
plt.legend()
plt.grid()
plt.savefig('RHO.png',dpi=500)
plt.clf()

plt.figure(2)
plt.plot(x_ref,u_ref,linewidth=1.5,color='black',label='Reference')
plt.plot(x_tvd,u_tvd,linewidth=1.5,label='TVD (van-Leer)')
plt.plot(x_thinc,u_thinc,linewidth=1.5,label='THINC')
plt.xlim(-5,5)
plt.xlabel(r'$x$')
plt.ylabel(r'$u$')
plt.legend()
plt.grid()
plt.savefig('VEL.png',dpi=500)
plt.clf()

plt.figure(3)
plt.plot(x_ref,p_ref,linewidth=1.5,color='black',label='Reference')
plt.plot(x_tvd,p_tvd,linewidth=1.5,label='TVD (van-Leer)')
plt.plot(x_thinc,p_thinc,linewidth=1.5,label='THINC')
plt.xlim(-5,5)
plt.xlabel(r'$x$')
plt.ylabel(r'$p$')
plt.legend()
plt.grid()
plt.savefig('PRS.png',dpi=500)
plt.clf()

plt.figure(4)
plt.plot(x_ref,alpha_1_ref,linewidth=1.5,color='black',label='Reference')
plt.plot(x_tvd,alpha_1_tvd,linewidth=1.5,label='TVD (van-Leer)')
plt.plot(x_thinc,alpha_1_thinc,linewidth=1.5,label='THINC')
plt.xlim(-5,5)
plt.xlabel(r'$x$')
plt.ylabel(r'$\alpha_1$')
plt.legend()
plt.grid()
plt.savefig('VOL.png',dpi=500)
plt.clf()
